### ISSUE TITLE
ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory 

### ISSUE THREAD

**Issue by StanSilas** [Franck-Dernoncourt/NeuroNER#66]
I have ubuntu 16.04 64gb ram, corei7 6th gen,  nvidia quaddro m1000m 2gb graphics card, 

I am following your tutorial step by step (https://github.com/Franck-Dernoncourt/NeuroNER/blob/master/install_ubuntu.md)  for tensorflow gpu variant. 

When i execute any of the commands to run NeuroNER I get the following errors: 

```
CUDA_VISIBLE_DEVICES="" python3.5 ./src/main.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./src/main.py", line 13, in <module>
    from neuroner import NeuroNER
  File "/home/vivek/NeuroNER-master/src/neuroner.py", line 3, in <module>
    import train
  File "/home/vivek/NeuroNER-master/src/train.py", line 2, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```  

However I when I run it using 
```
wget https://raw.githubusercontent.com/Franck-Dernoncourt/NeuroNER/master/install_ubuntu.sh; bash install_ubuntu.sh
```  
It runs fine. 

I looked at https://stackoverflow.com/questions/41991101/importerror-libcudnn-when-running-a-tensorflow-program but I didn't understand the solutions.

Please help.

**Comment by leeyjjoel** [comment]
Hey Stansilas,

 I believe you are facing an error due to cuDNN 6 (NVIDIA's GPU-accelerated library of primitives for deep neural networks) not being installed. As a result, tensorflow is unable to utilize your GPU and thus throws you an error. In order to fix this you should perform the following steps 

1. Go to https://developer.nvidia.com/rdp/form/cudnn-download-survey and sign up as a member

2.  Sign in and download cuDNN 7.1 for CUDA 9.1 

3.   Extract the cuDNN file by running ```tar xvzf cuDNN-8.0-linux-x64-v5.1-ga.tgz ```

4. ```sudo cp -P cuda/include/cudnn.h /usr/local/cuda/include```
5.  ```sudo cp -P cuda/lib64/libcudnn* /usr/local/cuda/lib64 ``` These two commands basically copy C++ header files to a location that tensorflow can recognize 
 
6.  ```sudo chmod a+r /usr/local/cuda/include/cudnn.h /usr/local/cuda/lib64/libcudnn*```
  Allow programs to read from these two files

Hope this helps!

**Comment by StanSilas** [comment]
Thank you so much for the very detailed reply!

**Comment by bharatsush** [comment]
export following stuff working for me:
Add following line to .bashrc

$export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda-8.0/lib64"
$export CUDA_HOME=/usr/local/cuda-8.0

Run .bashrc
$source ~/.bashrc
